const weatherModesDict = {
  1: 'CLEAR_DAY',
  2: 'PARTLY_CLOUDY_DAY',
  3: 'PARTLY_CLOUDY_DAY',
  4: 'PARTLY_CLOUDY_DAY',
  5: 'CLOUDY',
  6: 'CLOUDY',
  7: 'CLOUDY',
  8: 'FOG',
  9: 'RAIN',
  10: 'RAIN',
  11: 'RAIN',
  12: 'RAIN',
  13: 'RAIN',
  14: 'RAIN',
  15: 'RAIN',
  16: 'WIND',
  17: 'CLOUDY',
  18: 'PARTLY_CLOUDY_DAY',
  19: 'SNOW',
  20: 'SNOW',
  21: 'SLEET',
  22: 'SLEET',
  23: 'RAIN',
  24: 'SLEET',
  25: 'CLEAR_DAY',
  26: 'CLEAR_DAY',
  27: 'WIND',
  28: 'CLEAR_NIGHT',
  29: 'CLEAR_NIGHT',
  30: 'PARTLY_CLOUDY_NIGHT',
  31: 'PARTLY_CLOUDY_NIGHT',
  32: 'PARTLY_CLOUDY_NIGHT',
  33: 'PARTLY_CLOUDY_NIGHT',
  34: 'RAIN',
  35: 'RAIN',
  36: 'RAIN',
  37: 'RAIN',
  38: 'WIND',
  39: 'SNOW'
}

export default weatherModesDict;
